### ISSUE TITLE
depthai-viewer  Exiting... in windows OS

### ISSUE THREAD

**Issue by green512** [luxonis/depthai-viewer#31]
output:
Backend started successfully.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Lib\site-packages\depthai_viewer\_backend\main.py", line 26, in <module>
    sentry_sdk.init(
  File "C:\Python311\Lib\site-packages\depthai_viewer\venv-0.1.4\Lib\site-packages\sentry_sdk\hub.py", line 121, in _init
    client = Client(*args, **kwargs)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\depthai_viewer\venv-0.1.4\Lib\site-packages\sentry_sdk\client.py", line 143, in __init__
    self._init_impl()
  File "C:\Python311\Lib\site-packages\depthai_viewer\venv-0.1.4\Lib\site-packages\sentry_sdk\client.py", line 223, in _init_impl
    self.integrations = setup_integrations(
                        ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\depthai_viewer\venv-0.1.4\Lib\site-packages\sentry_sdk\integrations\__init__.py", line 109, in setup_integrations
    for integration_cls in iter_default_integrations(
  File "C:\Python311\Lib\site-packages\depthai_viewer\venv-0.1.4\Lib\site-packages\sentry_sdk\integrations\__init__.py", line 41, in iter_default_integrations
    yield getattr(import_module(module), cls)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Python311\Lib\site-packages\depthai_viewer\venv-0.1.4\Lib\site-packages\sentry_sdk\integrations\fastapi.py", line 22, in <module>
    import fastapi  # type: ignore
    ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "C:\Python311\Lib\site-packages\fastapi\applications.py", line 16, in <module>
    from fastapi import routing
  File "C:\Python311\Lib\site-packages\fastapi\routing.py", line 24, in <module>
    from fastapi.dependencies.models import Dependant
  File "C:\Python311\Lib\site-packages\fastapi\dependencies\models.py", line 3, in <module>
    from fastapi.security.base import SecurityBase
  File "C:\Python311\Lib\site-packages\fastapi\security\__init__.py", line 1, in <module>
    from .api_key import APIKeyCookie as APIKeyCookie
  File "C:\Python311\Lib\site-packages\fastapi\security\api_key.py", line 3, in <module>
    from fastapi.openapi.models import APIKey, APIKeyIn
  File "C:\Python311\Lib\site-packages\fastapi\openapi\models.py", line 103, in <module>
    class Schema(BaseModel):
  File "C:\Python311\Lib\site-packages\depthai_viewer\venv-0.1.4\Lib\site-packages\pydantic\main.py", line 291, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\depthai_viewer\venv-0.1.4\Lib\site-packages\pydantic\utils.py", line 256, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "C:\Python311\Lib\inspect.py", line 2715, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'not' is not a valid parameter name
Exiting...

**Comment by zrezke** [comment]
Hey @green512 - Huh, that's very interesting. Looks like a fastapi crash in the sentry_sdk which we use for error reporting, ironic. I think there is a large chance it will work if you install it using a lower python version like 3.10.

**Comment by zrezke** [comment]
Relevant fastapi issue https://github.com/tiangolo/fastapi/issues/5048

**Comment by zrezke** [comment]
Closing due to inactivity.
